### ISSUE TITLE
Remove `index.php` and `?controller=<controller>` from URL

### ISSUE THREAD

**Issue by cyberhck** [biv3k/blogMVC#1]
First things first:
Getting rid of index.php in URL is really easy.

just enable Rewrite module using: `a2enmod rewrite` in ubuntu, (Might need elevated permissions (sudo)). Then restart your server,

Tell your .htaccess to direct each and every request to index.php except for directories and files.

Then instead of having ?controller = , you can do something like /controller_name/method_name/argument1/argument2/argument3, you can explode with `/` and make it work.

PS, I couldn't find your call to routes.php anywhere.

**Comment by biv3k** [comment]
Will do that for sure. Thanks!
And routes.php is called by layout.php which is in Views directory

**Comment by cyberhck** [comment]
You're not supposed to call routes.php from a view stuff, view shouldn't know anything about controller. I've a similar type of project: https://github.com/cyberhck/poc_decorators notice I've got a request class which is used by request.php, we determine, which method on which class is to be called. And now, in your current situation, you'll never be able to do anything using `header()` function since you already sent out the output to browser even before you call your function, what if you want to change title, and so on. So what you should do is, call your controller's method, and that method will parse the view :)
